diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
user.name=Joostvanl
user.email=vanleeuwaarden@gmail.com
safe.directory='%Z///192.168.1.117/web/
safe.directory='//192.168.1.117/web/'
safe.directory=Z:/
safe.directory=Z:\
safe.directory=%(prefix)///192.168.1.117/web/.git
